"""baseline existing schema

Revision ID: 24c8e3994379
Revises:
Created: 2026-10-02 08:49:15.146451
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "24c8e3994379"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Level", sa.String(), nullable=True),
        sa.Column("Category", sa.String(), nullable=True),
        sa.Column("Message", sa.Text(), nullable=True),
        sa.Column("Value", sa.Float(), nullable=True),
        sa.Column("Threshold", sa.Float(), nullable=True),
        sa.Column("Source", sa.String(), nullable=True),
        sa.Column("Timestamp", sa.DateTime(), nullable=True),
        sa.Column("Resolved", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_records_id"), "alert_records", ["id"], unique=False)
    op.create_table(
        "etl_run_manifests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("rows_ingested", sa.Integer(), nullable=True),
        sa.Column("rows_quarantined", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_etl_run_manifests_id"), "etl_run_manifests", ["id"], unique=False)
    op.create_index(
        op.f("ix_etl_run_manifests_run_id"), "etl_run_manifests", ["run_id"], unique=True
    )
    op.create_table(
        "inventory_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Date", sa.DateTime(), nullable=True),
        sa.Column("Product", sa.String(), nullable=True),
        sa.Column("Stock_Qty", sa.Integer(), nullable=True),
        sa.Column("Incoming_Qty", sa.Integer(), nullable=True),
        sa.Column("Outgoing_Qty", sa.Integer(), nullable=True),
        sa.Column("Reorder_Point", sa.Integer(), nullable=True),
        sa.Column("Max_Capacity", sa.Integer(), nullable=True),
        sa.Column("Unit_Price", sa.Float(), nullable=True),
        sa.Column("Supplier", sa.String(), nullable=True),
        sa.Column("Created_At", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inventory_records_id"), "inventory_records", ["id"], unique=False)
    op.create_table(
        "kpi_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Date", sa.DateTime(), nullable=True),
        sa.Column("KPI_Name", sa.String(), nullable=True),
        sa.Column("KPI_Value", sa.Float(), nullable=True),
        sa.Column("Category", sa.String(), nullable=True),
        sa.Column("Created_At", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kpi_history_id"), "kpi_history", ["id"], unique=False)
    op.create_table(
        "machine_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Date", sa.DateTime(), nullable=True),
        sa.Column("Machine_ID", sa.String(), nullable=True),
        sa.Column("Status", sa.String(), nullable=True),
        sa.Column("Speed_RPM", sa.Float(), nullable=True),
        sa.Column("Temperature_C", sa.Float(), nullable=True),
        sa.Column("Vibration_mm", sa.Float(), nullable=True),
        sa.Column("Power_Usage_pct", sa.Float(), nullable=True),
        sa.Column("Downtime_min", sa.Integer(), nullable=True),
        sa.Column("Line", sa.String(), nullable=True),
        sa.Column("Created_At", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_machine_records_id"), "machine_records", ["id"], unique=False)
    op.create_table(
        "production_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Date", sa.DateTime(), nullable=True),
        sa.Column("Line", sa.String(), nullable=True),
        sa.Column("Shift", sa.String(), nullable=True),
        sa.Column("Product", sa.String(), nullable=True),
        sa.Column("Machine_ID", sa.String(), nullable=True),
        sa.Column("Worker_ID", sa.String(), nullable=True),
        sa.Column("Target_Qty", sa.Integer(), nullable=True),
        sa.Column("Actual_Qty", sa.Integer(), nullable=True),
        sa.Column("Good_Qty", sa.Integer(), nullable=True),
        sa.Column("Reject_Qty", sa.Integer(), nullable=True),
        sa.Column("Cycle_Time_sec", sa.Float(), nullable=True),
        sa.Column("Created_At", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_production_records_id"), "production_records", ["id"], unique=False)
    op.create_table(
        "quality_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Date", sa.DateTime(), nullable=True),
        sa.Column("Product", sa.String(), nullable=True),
        sa.Column("Line", sa.String(), nullable=True),
        sa.Column("Defect_Type", sa.String(), nullable=True),
        sa.Column("Defect_Count", sa.Integer(), nullable=True),
        sa.Column("Inspected_Qty", sa.Integer(), nullable=True),
        sa.Column("Severity", sa.String(), nullable=True),
        sa.Column("Inspector_ID", sa.String(), nullable=True),
        sa.Column("Created_At", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quality_records_id"), "quality_records", ["id"], unique=False)
    op.create_table(
        "quarantine_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("source_file", sa.String(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=True),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.Column("raw_payload", sa.Text(), nullable=True),
        sa.Column("quarantined_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quarantine_records_id"), "quarantine_records", ["id"], unique=False)
    op.create_index(
        op.f("ix_quarantine_records_run_id"), "quarantine_records", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_quarantine_records_source_file"),
        "quarantine_records",
        ["source_file"],
        unique=False,
    )
    op.create_table(
        "worker_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Date", sa.DateTime(), nullable=True),
        sa.Column("Worker_ID", sa.String(), nullable=True),
        sa.Column("Line", sa.String(), nullable=True),
        sa.Column("Shift", sa.String(), nullable=True),
        sa.Column("Hours_Worked", sa.Float(), nullable=True),
        sa.Column("Units_Produced", sa.Integer(), nullable=True),
        sa.Column("Defects_Caused", sa.Integer(), nullable=True),
        sa.Column("Attendance", sa.String(), nullable=True),
        sa.Column("Overtime_hrs", sa.Float(), nullable=True),
        sa.Column("Created_At", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_worker_records_id"), "worker_records", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_records_id'), table_name='worker_records')
    op.drop_table('worker_records')
    op.drop_index(op.f('ix_quarantine_records_source_file'), table_name='quarantine_records')
    op.drop_index(op.f('ix_quarantine_records_run_id'), table_name='quarantine_records')
    op.drop_index(op.f('ix_quarantine_records_id'), table_name='quarantine_records')
    op.drop_table('quarantine_records')
    op.drop_index(op.f('ix_quality_records_id'), table_name='quality_records')
    op.drop_table('quality_records')
    op.drop_index(op.f('ix_production_records_id'), table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_machine_records_id'), table_name='machine_records')
    op.drop_table('machine_records')
    op.drop_index(op.f('ix_kpi_history_id'), table_name='kpi_history')
    op.drop_table('kpi_history')
    op.drop_index(op.f('ix_inventory_records_id'), table_name='inventory_records')
    op.drop_table('inventory_records')
    op.drop_index(op.f('ix_etl_run_manifests_run_id'), table_name='etl_run_manifests')
    op.drop_index(op.f('ix_etl_run_manifests_id'), table_name='etl_run_manifests')
    op.drop_table('etl_run_manifests')
    op.drop_index(op.f('ix_alert_records_id'), table_name='alert_records')
    op.drop_table('alert_records')
    # ### end Alembic commands ###

    Downgrades here exist only while the schema is still young. Once a table
    holds production rows, a downgrade is a data-loss decision and belongs in a
    reviewed runbook, not in a default path -- which is why dropping a table is
    written explicitly rather than inherited from autogenerate.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_worker_records_id"), table_name="worker_records")
    op.drop_table("worker_records")
    op.drop_index(op.f("ix_quarantine_records_source_file"), table_name="quarantine_records")
    op.drop_index(op.f("ix_quarantine_records_run_id"), table_name="quarantine_records")
    op.drop_index(op.f("ix_quarantine_records_id"), table_name="quarantine_records")
    op.drop_table("quarantine_records")
    op.drop_index(op.f("ix_quality_records_id"), table_name="quality_records")
    op.drop_table("quality_records")
    op.drop_index(op.f("ix_production_records_id"), table_name="production_records")
    op.drop_table("production_records")
    op.drop_index(op.f("ix_machine_records_id"), table_name="machine_records")
    op.drop_table("machine_records")
    op.drop_index(op.f("ix_kpi_history_id"), table_name="kpi_history")
    op.drop_table("kpi_history")
    op.drop_index(op.f("ix_inventory_records_id"), table_name="inventory_records")
    op.drop_table("inventory_records")
    op.drop_index(op.f("ix_etl_run_manifests_run_id"), table_name="etl_run_manifests")
    op.drop_index(op.f("ix_etl_run_manifests_id"), table_name="etl_run_manifests")
    op.drop_table("etl_run_manifests")
    op.drop_index(op.f("ix_alert_records_id"), table_name="alert_records")
    op.drop_table("alert_records")
    # ### end Alembic commands ###
